### ISSUE TITLE
Issue Template references wrong namespace

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-flight#100]
### Please verify the version of auro-flight you have installed

2.4.0

### Please describe the bug

I think the NPM box on this Issue Template is pointed to an old namespace:

<img width="487" alt="image" src="https://github.com/AlaskaAirlines/auro-flight/assets/7005799/13dc67e0-8222-4978-be4d-6f51aa1d6d7f">

### Reproducing the error on the docsite

None

**Comment by blackfalcon** [comment]
Address with commit 

- 776e5ed
