### ISSUE TITLE
auro-flight: update design per new blueprint

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-flight#105]
### General Support Request

Update design of `auro-flight` per the new blueprint

### Possible Solution

Leave as is

### Additional context

Here is the blueprint: https://www.figma.com/file/gZLtvCfoKJcWhvMsy6Otoa/Flight?type=design&node-id=2402-679&mode=design&t=CXV0eTjn6iFGJWl6-0

### Exit criteria

Ticket can be closed when blueprint design is implemented and the UI changes are approved by the design team

**Comment by jordanjones243** [comment]
Moving this ticket to "Blocked" for the time being, as we uncovered a bug in the design tokens for applying font-weights to text.

**Comment by erikalanghauser** [comment]
@braven112 - would it be possible to get this re-prioritized? Mobile text sizing does not match the blueprint, which makes us non-compliant for DOT regs that require us to match city pair text sizing to codeshare and other required disclosures. Right now the city pairs are larger than the disclosures which is a no-no.

**Comment by Patrick-Daly-AA** [comment]
@erikalanghauser , can you provide a picture of the issue you're seeing on Auro Flight for mobile?  Looking on the doc site, the font sizes look identical, but we're going to verify they are the same in the code.
