### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flight#14]
# User story

The scope of this story is to encompass the following open issues to be delivered. The following list is prioritized.

## Prior to next major release 

It is **important that we communicate prior to the next major release** that we will be changing the npm namespace. 

- [ ] https://github.com/AlaskaAirlines/auro-flight/issues/20

## Dependency

- [ ] https://github.com/AlaskaAirlines/auro-iata/issues/2
- [ ] a11y features #8 

## Outline subtasks or tasks

- [ ] update boolean API #11 
- [ ] SEO structured data #5 
- [ ] upgrade #7 

## Development process

This is a placeholder issue for all the issues to be in a single release. As each issue is put into play, please update the issue as IN PROGRESS and move it into the WIP column. Please leave this issue in TO DO until all linked issues are completed.

## Definition of “Done” (exit criteria)

This issue will be considered complete and all features released once all issues listed are considered complete.

**Comment by braven112** [comment]
closing this rc in favor of issues and milestones
