### ISSUE TITLE
Component overflows in 2 column layout at certain screen widths

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-flight#19]
## Describe the bug
For certain layout configurations and screen widths, the auro-flight component overflows its container. This is best explained with a screenshot.
![image](https://user-images.githubusercontent.com/4992896/127906763-b2d77d92-03b5-4126-9c73-d29c67693463.png)

This happens for flights that are:
1. not able to take up the whole screen (e.g. 2 column layout)
2. have multiple stops
3. have layover durations

Depending on how you look at it, this might be a feature request. I'll start it as a bug for now.

## To Reproduce
1. Go to this [CodePen demo](https://codepen.io/geoff-rich/pen/Exmpjav)
2. Reduce the screen width to 750px. 
3. Notice that the flight overflows its container without switching to mobile view (i.e. summarizing the stops as "3 stops")

## Expected behavior
The auro-flight component responds to container width instead of only looking at screen width.

Yes, this is basically asking for container queries, though there may be ways to work around it until container queries are supported in browsers.

## Additional context
We ran into this on our disruptions site, which renders two flights side-by-side when not in mobile view. At certain screen widths, the flight breaks out of the container and information is cut off. See the screenshot below -- this was taken at 700px. "pm" is cut off of the time.

We are working around this for now by forcing to a mobile layout at a higher breakpoint than originally intended.

![image](https://user-images.githubusercontent.com/4992896/127907423-990772c6-2836-47df-ab18-9e67c449bcb0.png)

**Comment by blackfalcon** [comment]
Review https://www.npmjs.com/package/lit-media-query as a possible solution for this issue.

**Comment by blackfalcon** [comment]
An official container query spec is in the works
https://css-tricks.com/say-hello-to-css-container-queries/

Here is a polyfill that is based on that spec
https://github.com/jsxtools/cqfill

**Comment by geoffrich** [comment]
This was resolved by https://github.com/AlaskaAirlines/auro-flightline/pull/23. I think this issue can be closed.
