### ISSUE TITLE
Auro-Flight Blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-flight#21]
# Blueprint
We need a blueprint for auro-flight that matches the features we have currently on our doc site.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by blackfalcon** [comment]
@leeejune this is not a must-have by any stretch, but was wondering what the effort would be to take what has been created for this element and convert that to a blueprint?

**Comment by leeejune** [comment]
It'd take the same effort as other blueprints I've created for existing components. Should we prioritize this?

**Comment by jordanjones243** [comment]
Blueprint design completed: https://www.figma.com/file/gZLtvCfoKJcWhvMsy6Otoa/Flight?type=design&node-id=322-298&mode=design&t=CXV0eTjn6iFGJWl6-0

**Comment by leeejune** [comment]
@jordanjones243 should this be in "Blocked" instead? or another issue needs to be created for the text bug?

**Comment by jordanjones243** [comment]
> @jordanjones243 should this be in "Blocked" instead? or another issue needs to be created for the text bug?

You can block this. Make note of why and we need to figure out how we can fix this issue, that could be in this comment or in an issue. I am not sure if this is a "bug" for auro-flight though because there was no existing blueprint, so the current design without the font-weight change is not wrong.

**Comment by leeejune** [comment]
The weight of the time is rendering incorrectly. After discussing with engineering, we've determined that there is an issue with outdated code within the component. Work needs to be done to figure out the problem and have the 500 weight render correctly.

**Comment by Patrick-Daly-AA** [comment]
@Patrick-Daly-AA , make followup investigation work item later for why this behavior described above is happening
