### ISSUE TITLE
Accept UTC time for departure and arrival 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flight#26]
## Is your feature request related to a problem? Please describe.

The current API accepts a string for the flight arrival and departure times. The current spec defines this as `7:30 am`.

## Describe the solution you'd like

This requirement means that data that usually comes into an app as UTC requires conversion prior to entering the string into the element. 

The element should be updated to require a UTC time code versus a converted string. This will ensure consistency of entered data into the element and reduce the dependency on the user to pre-convert time prior to use with the element. 

## Exit criteria 

The element's departure and arrival API will only accept a UTC time code as a value and will use internal logic to convert to a standard display of time.

**Comment by gusnaughton** [comment]
It would be great to have a feature to toggle between local time, relative time, and military time as well - some standard format strings could probably be decided on.

**Comment by blackfalcon** [comment]
> It would be great to have a feature to toggle between local time, relative time, and military time as well - some standard format strings could probably be decided on.

I see what you are going for, but is that a feature people want? Relative time or a 24hr clock really seems like a reach. I can maybe see departure and arrival times in your time zone.

**Comment by blackfalcon** [comment]
The scope of this issue was explored with the spike PR. After further review of data received from the FlightResultsAPI it was learned that the flight search team has a BFF that converts a lot of data to a simpler string for consumption in the custom element. 

It was discussed that the data coming from the API is not of proprietary nature and others is no need to pre-process the data in a BFF. Therefore the following revision is suggested to update the `departureTime` and `arrivalTime` props to access the full datetime UTC code that comes from the API. 

```
departureTime="2022-04-13T01:10:00-07:00"
arrivalTime="2022-04-13T12:30:00-04:00"
```

Getting this datetime UTC code also enables the element to address additional capabilities that were manually addressed in the current version. That being the `daysChanged` property. With this update, the element can easily calculate the days changed without that being pre-processed as well. 

Additionally getting this data is required for the issue of SEO and structured data.  The `departureTime` and `arrivalTime` nodes require the date to be in its UTC format.
