### ISSUE TITLE
Display arrival and departure city as primary text

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-flight#32]
## Is your feature request related to a problem? Please describe.
I would like to use this component to display all the segments in a reservation. For example, a guest has a reservation like so:

PDX-SEA
SEA-DCA
DCA-SEA
SEA-PDX

The auro-flight component seems to be a good fit, but it currently emphasizes the departure and arrival time (great for shopping  search results). However, in the post-booking path (when viewing a reservation), the emphasis is now on departure/arrival locations. See 1st screenshot below.

## Describe the solution you'd like
1. Swap the departure/arrival time with departure/arrival city location.
2. Another component specifically designed for flights in a reservation. Is there an opportunity to unify how all flights in a reservation should look? See the mobileweb screenshot below.

## Describe alternatives you've considered
None

## Additional context
Desired UI for Preorder food
![image](https://user-images.githubusercontent.com/3304352/171723484-fada2077-d458-404b-a544-8129a0d967e3.png)

And here's the current ViewRes on m.alaskaair.com
![image](https://user-images.githubusercontent.com/3304352/171724163-2322c531-2713-49e4-a2ba-a95757d64a27.png)

**Comment by jordanchang** [comment]
And here is what ViewRes looks like on desktop:
![image](https://user-images.githubusercontent.com/3304352/171726412-2335b27b-1616-4898-a904-9ab812a1b8f0.png)

**Comment by blackfalcon** [comment]
It would be great if another designer could team up with @leeejune to help see if there is a variant we can do with the current auro-flight and auro-flightline elements to be useable in these other spaces.

**Comment by blackfalcon** [comment]
@jordanchang do you have a status update for this? To move this forward, please have your product designer consult with @leeejune to see if there is a path forward in the current flight element or if there are other opportunities. 

I am labeling this issue as BLOCKED as there needs to be a conversation before we can have a resolution.

**Comment by blackfalcon** [comment]
This request appears to have been abandoned. @jordanchang if you are still interested in persuing this design feature, please have your team's designer reach out to @leeejune for consultation.
