### ISSUE TITLE
Flight content use audit

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flight#42]
# General Support Request

Design leadership had reached out asking for an audit of AS.com and its use/non-use of the auro flight component. 

## Support request

Review with teams that are and are not using auro-flight and collect data as to their use cases. 

## Exit criteria 

This work will be considered complete once a report of the findings has been completed.

**Comment by blackfalcon** [comment]
The exit criteria is not 100% solid. First step is to generate report of findings. I would argue that once that is completed this issue should be closed and any new requests be addressed in a new ticket.

**Comment by leeejune** [comment]
Flight info audit completed. Will be reviewing with Tom, Ona, and Shelby tomorrow.

https://www.figma.com/file/fF5ACbZcUJZ8Z6DGYbCghd/Flight-Details?node-id=141%3A21126

**Comment by leeejune** [comment]
Reviewed by Tom, Ona, and Shelby. Will be getting reviewed by Natalie.

**Comment by leeejune** [comment]
Reviewed by Natalie. Will be meeting with Ona and Tom tomorrow for next steps.
