### ISSUE TITLE
Screen Reader Not Reading Flight Info Table for Older Versions of MacOS

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-flight#45]
## Describe the bug
Running on MacOS Big Sur v 11.6.8, the screen reader not reading flight info table.

Related to AB#792332

## Expected behavior
Screen reader picks up the context blocks we've added to the component

## Desktop (please complete the following information):

 - OS: MacOS
 - Version: Big Sur 11.6.8

Video recording pending.

**Comment by blackfalcon** [comment]
Any review of this issue is pending more details.

**Comment by aesthetiques** [comment]
We've validated that what we were seeing is expected behavior, and we're all good on our side.
