### ISSUE TITLE
Missing feature: red layover badge for overnight layovers

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-flight#47]
## Describe the bug
In preparing for launch of international and interline flights on the flight results microsite, we have noticed that the auro-flight feature for showing overnight layovers in red is missing. This is spec'd out in the figma blueprints.

var(--auro-color-alert-error-on-light)

![image](https://user-images.githubusercontent.com/34354487/202553084-14b5c14a-4cf9-4a90-85f4-f9c124f09238.png)

## To Reproduce

* Go to https://www.alaskaair.com/search-test/results?A=1&O=psg&D=alw&OD=2023-03-23&OT=Anytime&RT=false&UPG=none
* Many flights are arriving next day, which accurately shows in the +1 day; but the layover badges that are overnights are not showing in red.
* This layover is overnight and should be red

![image](https://user-images.githubusercontent.com/34354487/202536806-f749292c-9aae-46a0-ae8b-a1fb241dc6bc.png)

## Expected behavior

When layovers are overnight, the text in the badge appears in red as spec'd in the figma blueprint. 
var(--auro-color-alert-error-on-light)
https://www.figma.com/file/4e5FcfFlEhnSW9GveMlKnj/Flight-Line?node-id=160%3A7272&t=ISdg9FOgdAi5Licj-1
https://www.figma.com/file/4e5FcfFlEhnSW9GveMlKnj/Flight-Line?node-id=704%3A927&t=ISdg9FOgdAi5Licj-1

## Screenshots
See above, please.

**Comment by erikalanghauser** [comment]
CC: discussed this update with @leeejune prior to creating issue :)

**Comment by erikalanghauser** [comment]
![image](https://user-images.githubusercontent.com/34354487/202560319-8956e2c7-8b42-45f6-babc-a79eaa980adb.png)

![image](https://user-images.githubusercontent.com/34354487/202560341-a3d3e6af-9a5b-4d5c-a0f1-527915cfa89a.png)

**Comment by blackfalcon** [comment]
Issue scheduled for review with the team.

**Comment by blackfalcon** [comment]
The reported bug is determined to actually be a missing feature. A new issue/story will be created that will outline a solution to adding this feature between auro-flight and auro-flightline. 

More to come...

**Comment by blackfalcon** [comment]
The decision over whether a flight is +1 day or not happens with this calculation. 

https://github.com/AlaskaAirlines/auro-flight/blob/42fead90a2105141e06d99098c31d9d4984dca69/src/auro-flight-header.js#L57-L68

The output from that decision happens in this template 

https://github.com/AlaskaAirlines/auro-flight/blob/42fead90a2105141e06d99098c31d9d4984dca69/src/auro-flight-header.js#L93-L96

The additional colored UI that is requested in this issue is NOT part of the auro-flight component but is part of the auro-flightline component. Whether or not we can change the text color is not an issue, the real question is, how do we know exactly which leg of the flight is the overnight layover? 

Is this described in the flight data?

**Comment by aesthetiques** [comment]
![image](https://user-images.githubusercontent.com/25255197/205136421-1ec23668-f522-4702-bda4-bb1c63a01ee5.png)
@erikalanghauser, @blackfalcon and I were covering this issue. For the criteria, are we wanting to highlight layover duration or flight arrival time being next day? 

Ex above: Departs LAX 645pm, arrives HNL 10:55pm and has a 12 hour layover, taking us into the next day. Do we want this to be highlighted red? What do we consider as "arriving next day"?

**Comment by erikalanghauser** [comment]
@aesthetiques 'arriving next day' would mean that they are landing somewhere at 12:00am or later on the next date after the day they departed their origin.

**Comment by blackfalcon** [comment]
This issue will be resolved in the following issue

- https://github.com/AlaskaAirlines/auro-flightline/issues/42

There is not to be a release with auro-flight. This issue is now closed.
