### ISSUE TITLE
-1 Days unsupported (International Date Line)

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-flight#51]
## Describe the new Feature

As auro-flight begins being used in award flight shopping, international date line concerns need to be addressed.

For instance, take this flight:
https://www.google.com/travel/flights/booking?tfs=CAIQAhpEagwIAxIIL20vMDM0dGwSCjIwMjMtMDEtMDFyBwgBEgNITkwiHwoDR1VNEgoyMDIzLTAxLTAxGgNITkwqAlVBMgMyMDBwAYIBCwj___________8BQAFIAZgBAg&source=flre_fli_share&utm_campaign=sharing

This flight crosses the international date line, causing a "-1 Day". Auro-flight doesn't seem to support negative date calculations.

This will be an issue as we sell more western pacific rim -> HI flights.

## To Reproduce

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/7005799/208257102-8738de0d-4e58-470d-af4d-e87158c3a2e6.png">

## Expected behavior

-1 day to be displayed.

**Comment by blackfalcon** [comment]
I wouldn't call this a `bug`, but this is a new feature request. Re-classifying this issue. 

@leeejune we should talk with the UI design team about how to best illustrate this experience. `-1 Day` might not be the right way to do this?

The United example linked as the most minimal designation. I had to look hard to find the `-1 day`. 

<img width="1012" alt="Screen Shot 2022-12-27 at 4 34 13 PM" src="https://user-images.githubusercontent.com/181089/209739656-44404c49-a1f0-4a15-9ced-9e8372896e47.png">

Expedia actually shows this as a `+1 Day` O_O. 

<img width="914" alt="Screen Shot 2022-12-27 at 4 35 35 PM" src="https://user-images.githubusercontent.com/181089/209739861-aa83774a-aa49-4adb-be93-a1adc3361f9e.png">

**Comment by blackfalcon** [comment]
This issue requires further refinement with the team.

**Comment by blackfalcon** [comment]
As discussed with the team, the work appears to be minimal. Update the current +1 Day feature to understand the concept of -1 Day. 

Still need to consult with @leeejune and the other designers to be sure that we are simply going to update the current +1 Day UI with this feature. 

## specification 

Update the current javascript that determines +1 Day and support -1 Day

## Exit criteria 

This issue will be considered complete once we have a working example that uses the GUM to HNL example data and produces the correct results.

**Comment by blackfalcon** [comment]
As discussed with the team, the work appears to be minimal. Update the current +1 Day feature to understand the concept of -1 Day. 

Still need to consult with @leeejune and the other designers to be sure that we are simply going to update the current +1 Day UI with this feature. 

## specification 

Update the current javascript that determines +1 Day and support -1 Day

## Exit criteria 

This issue will be considered complete once we have a working example that uses the GUM to HNL example data and produces the correct results.

**Comment by blackfalcon** [comment]
Assigned to @leeejune for design feedback.

**Comment by leeejune** [comment]
Discussed issue with UI team. Will be reaching out to the research team about testing the "-1" solution.

**Comment by leeejune** [comment]
Research will be testing out the solution in future studies. Timeline is not clear, but research has informed me that it will be prioritized for the next study.

**Comment by leeejune** [comment]
Study shows the the "-1 day" solution works. Next steps are to add support for this feature.

[More details in this deck.](https://nam04.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Falaskaair.sharepoint.com%2F%3Ap%3A%2Fs%2FECOMt%2Fuxresearch%2FEYPv4hpSModIj9XAJ4Eb-BEB_Hx14UfoycvJCHT4E2fZeA%3Fe%3DcrESaj&data=05%7C01%7CJune.Lee%40alaskaair.com%7C38c19f606fc040a37d7108db36216ea8%7C0f44c5d442b045c2bf55d0fea8430d33%7C0%7C0%7C638163289449128280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t6%2BATpVVjZ3FYNFWKogwxJcNcR1xHIMVMVaLXPHgJd0%3D&reserved=0)

**Comment by gusnaughton** [comment]
This is a current issue in production:
<img width="1317" alt="image" src="https://github.com/AlaskaAirlines/auro-flight/assets/7005799/20fa52ce-0968-4ea4-8ed5-461ad18b64ea">

<img width="1175" alt="image" src="https://github.com/AlaskaAirlines/auro-flight/assets/7005799/2d0232fa-79de-4cf1-ab57-aaf338f00d8f">

**Comment by braven112** [comment]
@blackfalcon @irma-kurnia-alaska should this issue be closed now that #109 is merged?
