### ISSUE TITLE
Support smaller font sizes on mobile

### ISSUE THREAD

**Issue by cwilliams7** [AlaskaAirlines/auro-flight#55]
## Is your feature request related to a problem? Please describe.

The design team for Merch has a design for a mobile flight card that uses size 1.125rem font for the departure and arrival times:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/86806863/228914393-76dba43a-dd37-45c2-9167-c92ad73784f0.png">

The auro-flight component uses 1.75rem for these fonts and it cannot be adjusted directly.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/86806863/228914590-764dd6ce-eec8-423f-b71c-ada6ddb6f455.png">

## Describe the solution you'd like

I'd like the component either updated to allow for an input to control the mobile font size, with the default value being the same as today for backward compatibility or have the component updated to use 1.125rem for departure & arrival times on mobile screen sizes, there was some discussion on the Auro public channel that the behavior I am seeing might be a bug and the font size is supposed to be 1.125rem on mobile.

## Describe alternatives you've considered

I considered using javascript to reach into the shadow dom and modify the styles directly but this would be a brittle solution and doesn't address the underlying issue.

**Comment by blackfalcon** [comment]
Hey @cwilliams7 I am looking over the code for this element and we do not have any media query support. I am re-classing this as a FEATURE vs a BUG as this is not something that is broken, it's a capability that does not exist. 

@leeejune who is a designer we can work with to understand the missing capability?

**Comment by cwilliams7** [comment]
@blackfalcon, thanks for clarifying! @blackfalcon & @leeejune the designer would be Chloe L'Ecuyer.

**Comment by leeejune** [comment]
Erika has also brought this issue up. Would like to see this work refined.

**Comment by erikalanghauser** [comment]
Flight Search is planning to direct mobile user to the responsive microsite soon, and we are seeing the same wrapping issue with the time. The auro-flight blueprint does indicate smaller text sizes at the mobile breakpoint.

**Comment by leeejune** [comment]
This is the link to original redlines: https://www.figma.com/file/4e5FcfFlEhnSW9GveMlKnj/Flight-Line?type=design&node-id=160-7273&mode=design&t=fO8htQTrwZXcPRZs-11

**Comment by braven112** [comment]
We need to update the smallest breakpoint to use `var(--auro-text-heading-300-size-breakpoint-sm)`

**Comment by leeejune** [comment]
[Blueprint completed here](https://www.figma.com/file/gZLtvCfoKJcWhvMsy6Otoa/Flight?type=design&node-id=322-298&mode=design&t=6aDwJGD1FhZtUTTp-11)
